[package]
name = "tg-ws-proxy-core"
version = "0.4.0"
description = "High-performance Telegram MTProto WebSocket Proxy Core in Rust"
authors = ["nsvl"]
license = "MIT"
repository = "https://github.com/rxzsu/tg-ws-rust"
edition = "2024"
rust-version = "1.95.0"

[dependencies]
tokio = { version = "1.43", features = ["full"] }
tokio-rustls = "0.26"
rustls-pki-types = "1.10"
webpki-roots = "1.0"
aes = "0.9"
ctr = "0.10"
hmac = "0.13"
sha2 = "0.11"
byteorder = "1.5"
bytes = "1.9"
rand = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2.0"
http = "1.2"
httparse = "1.9"
h2 = "0.4"
socket2 = "0.5"
hex = "0.4"
base64 = "0.23"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "throughput"
harness = false
